spring:
    application:
        name: yagm
    datasource:
        url: 'jdbc:postgresql://localhost:5432/yagm'
        username: '${DB_USER}'
        password: '${DB_PASSWORD}'
    jpa:
        hibernate:
            ddl-auto: create-drop
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        defer-datasource-initialization: true
    sql:
        init:
            mode: always