spring:
    application:
        name: yagm
    datasource:
        url: 'jdbc:postgresql://localhost:5432/yagm'
        username: '${DB_USER}'
        password: '${DB_PASSWORD}'
    jpa:
        hibernate:
            ddl-auto: create-drop
        defer-datasource-initialization: true
    sql:
        init:
            mode: always

messages:
    clientAlreadyExists: "Client exception - Client already exists"
    clientDoesNotExist: "Client exception - Client does not exists"
    clientRegistered: "Client registered successfully"
    clientDeleted: "Client deleted successfully"
    invalidClientData: "Invalid client data"