CREATE TABLE IF NOT EXISTS public.clients
(
    phone_number integer NOT NULL,
    zip integer NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    address character varying(255) COLLATE pg_catalog."default",
    city character varying(255) COLLATE pg_catalog."default",
    country character varying(255) COLLATE pg_catalog."default",
    dni character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default",
    first_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT clients_pkey PRIMARY KEY (id),
    CONSTRAINT clients_dni_key UNIQUE (dni)
);


CREATE TABLE IF NOT EXISTS public.exercises
(
    recommended_max_reps integer NOT NULL,
    recommended_min_reps integer NOT NULL,
    recommended_sets integer NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    instructions character varying(255) COLLATE pg_catalog."default",
    muscle character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    tool character varying(255) COLLATE pg_catalog."default" NOT NULL,
    url character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT exercises_pkey PRIMARY KEY (id),
    CONSTRAINT exercises_muscle_check CHECK (muscle::text = ANY (ARRAY['BICEPS'::character varying, 'TRICEPS'::character varying, 'SHOULDER'::character varying, 'FOREARMS'::character varying, 'CHEST'::character varying, 'UPPER_BACK'::character varying, 'LATS'::character varying, 'QUADS'::character varying, 'FEMORAL'::character varying, 'CALVES'::character varying, 'ABS'::character varying]::text[]))
)
